version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
init: 
- cmd: git config --global core.autocrlf true 
- cmd: set DOTNET_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
before_build:
- cmd: dotnet restore -v Warning
build:
  project: NWebsec-CI.sln
  verbosity: minimal
test_script:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    pushd .\test\NWebsec.AspNetCore.Core.Tests\

    dotnet test -c release

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

    popd

    pushd .\test\NWebsec.AspNetCore.Middleware.Tests\

    dotnet test -c release

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

    popd

    pushd .\test\NWebsec.AspNetCore.Mvc.Tests\

    dotnet test -c release

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

    popd
after_test:
- ps: >-
    pushd .\src\NWebsec.AspNetCore.Core\

    dotnet pack -c release

    popd

    pushd .\src\NWebsec.AspNetCore.Middleware\

    dotnet pack -c release

    popd

    pushd .\src\NWebsec.AspNetCore.Mvc\

    dotnet pack -c release

    popd
artifacts:
- path: '**/NWebsec.AspNetCore.Core/bin/release/*.nupkg'
- path: '**/NWebsec.AspNetCore.Middleware/bin/release/*.nupkg'
- path: '**/NWebsec.AspNetCore.Mvc/bin/release/*.nupkg'
